project:
  type: website
  output-dir: docs

website:
  title: "fig project"
  navbar:
    left:
      - text: "|  The project  |"
        file: summary.qmd
        file: figanalysis.qmd
        file: figanalysistext.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual