project:
  type: website
  output-dir: docs

website:
  title: "fig project 2"
  site-url: https://sotiriahau.github.io/website
  navbar:
    left:
      - text: "|  The project  |"
        file: summary.qmd
      - figanalysis.qmd
      - figanalysistext.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual