project:
  type: website
  output-dir: docs

website:
  title: "fig project"
  navbar:
    left:
      - text: "| The project |"
        file: index2.qmd
      - text: "| Data Analysis (RAD-seq) - *Ficus* |"
        file: index.qmd
      - text: "| Comments |"
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

