project:
  type: website
  output-dir: docs

website:
  title: "fig project"
  navbar:
    left:
      - href: index.qmd
        text: | Data Analysis (RAD-seq) - *Ficus* |
      - href: about.qmd
      text: | <-- comments |

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

