project:
  type: website
  output-dir: docs

website:
  title: "fig project"
  navbar:
    left:
      - text: "|  The project  |"
        file: summary.qmd
      - text: "|  Data Analysis (RAD-seq) - *Ficus*  |"
        file: figanalysis.qmd
      - text: "|  Comments  |"
        file: figanalysistext.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

