project:
  type: website
  output-dir: docs

website:
  title: "fig project"
  navbar:
    left:
      - href: index.qmd
        text: Data analysis
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

